# Generated by Django 2.2.6 on 2020-03-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0090_auto_20200303_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyqty',
            name='diverted_to',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.Site'),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='diverted_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diversion', to='work.Site'),
        ),
    ]
