# Generated by Django 2.2.6 on 2020-03-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0091_auto_20200303_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyqty',
            name='diverted_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diversion', to='work.Site'),
        ),
    ]
