# Generated by Django 2.2.6 on 2020-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0093_auto_20200304_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='habitation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalsiteextra',
            name='habitation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='habitation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='habitation',
            field=models.CharField(max_length=100),
        ),
    ]
