# Generated by Django 2.2.6 on 2020-03-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0094_auto_20200304_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteextra',
            name='diversion_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.Site'),
        ),
        migrations.AddField(
            model_name='siteextra',
            name='diversion_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diverted_to', to='work.Site'),
        ),
    ]
