# Generated by Django 2.2.6 on 2020-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0095_auto_20200304_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteextra',
            name='diversion_to',
        ),
        migrations.RemoveField(
            model_name='siteextra',
            name='diversion_to',
        ),
        migrations.AddField(
            model_name='historicalsiteextra',
            name='diversion_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteextra',
            name='diversion_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
