# Generated by Django 2.2.6 on 2020-03-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0096_auto_20200304_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsurveyqty',
            name='diverted_to',
        ),
        migrations.RemoveField(
            model_name='surveyqty',
            name='diverted_to',
        ),
    ]
