# Generated by Django 3.0.4 on 2020-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0099_boq_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='qty',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
