# Generated by Django 3.0.4 on 2020-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0100_boq_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='district',
            field=models.CharField(choices=[('BISHNUPUR', 'BISHNUPUR'), ('CHURACHANDPUR', 'CHURACHANDPUR'), ('CHANDEL', 'CHANDEL'), ('IMPHAL EAST', 'IMPHAL EAST'), ('IMPHAL WEST', 'IMPHAL WEST'), ('SENAPATI', 'SENAPATI'), ('THOUBAL', 'THOUBAL'), ('TAMENGLONG', 'TAMENGLONG'), ('UKHRUL', 'UKHRUL')], max_length=50),
        ),
    ]
