# Generated by Django 3.0.4 on 2020-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0102_auto_20200313_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='nature',
            field=models.CharField(choices=[('SUPPLY', 'SUPPLY'), ('ERECTION', 'ERECTION')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boq',
            name='region',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBAN', 'URBAN')], max_length=50),
        ),
    ]
