# Generated by Django 2.2.6 on 2020-04-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0103_auto_20200313_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('submitted', 'submitted'), ('passed', 'passed'), ('issue', 'issue')], max_length=30, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
    ]
