# Generated by Django 2.2.6 on 2020-04-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0104_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('passed', 'passed'), ('issue', 'issue')], default=None, max_length=30, null=True),
        ),
    ]
