# Generated by Django 2.2.6 on 2020-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0105_auto_20200407_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(blank=True, choices=[(None, None), ('submitted', 'submitted'), ('passed', 'passed'), ('issue', 'issue')], default=None, max_length=30, null=True),
        ),
    ]
