# Generated by Django 2.2.6 on 2021-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0107_billing_billno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteextra',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
