# Generated by Django 2.2.6 on 2021-02-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0108_auto_20210128_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='daughter_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.Site'),
        ),
        migrations.AddField(
            model_name='site',
            name='daughter_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter', to='work.Site'),
        ),
    ]
