# Generated by Django 2.2.6 on 2020-01-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0010_auto_20200117_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='consumer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
