# Generated by Django 2.2.6 on 2020-01-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0011_consumer_consumer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumer',
            unique_together=set(),
        ),
    ]
