# Generated by Django 2.2.6 on 2020-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0014_auto_20200602_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
