# Generated by Django 2.2.6 on 2021-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0015_auto_20200602_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
