# Generated by Django 2.2.6 on 2021-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0017_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='cinfra_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
